import { useEffect, useRef, useState } from 'react';
import { ApiError, createSession, ensureIdentity, getCurrent, getSession, saveAnswer, sendEvent, submitSession, type Question, type Session } from './api';
import { cacheKey, mergeServerDraft, updateAnswer, type AnswerValue, type DraftState } from './state';

const fieldLabels:Record<string,string>={choice:'选项',reason:'原因',name:'名称',frequency:'使用频率',typicalTask:'典型任务',independence:'独立程度',work:'作品或项目',action:'你的动作',result:'结果或反馈',time:'时间',status:'经历状态',goal:'目标',target:'目标任务',text:'文字说明'};
const present=(value:unknown)=>value!==undefined&&value!==''&&(!(typeof value==='string')||value.trim().length>0)&&(!Array.isArray(value)||value.length>0);
export const questionComplete=(question:Question,value:AnswerValue|undefined)=>{if(!question.required)return true;if(question.type!=='compound')return present(value);if(!value||typeof value!=='object'||Array.isArray(value))return false;const object=value as Record<string,unknown>,fields=question.fields??[];if(!fields.every(field=>{const active=!field.condition||object[field.condition.field]===field.condition.equals;if(!active)return object[field.id]===undefined;const v=object[field.id];if((field.required||(field.requiredWhenCondition&&active))&&!present(v))return false;if(field.type==='integer'&&present(v)&&((v as number)<(field.min??-Infinity)||(v as number)>(field.max??Infinity)))return false;return true;}))return false;const combined=fields.find(field=>field.combinedLength&&(!field.condition||object[field.condition.field]===field.condition.equals))?.combinedLength;if(combined){const length=combined.fields.map(id=>String(object[id]??'')).join('').length;if(length<combined.min||length>combined.max)return false;}return true;};

export function QuestionInput({question,value,onChange}:{question:Question;value:AnswerValue|undefined;onChange:(value:AnswerValue)=>void}) {
  if(question.type==='compound') { const objectValue=(value&&typeof value==='object'&&!Array.isArray(value)?value:{}) as Record<string,string|string[]|number>; const setField=(id:string,next:string|string[]|number)=>{const updated={...objectValue,[id]:next};for(const field of question.fields??[])if(field.condition&&field.condition.field===id&&next!==field.condition.equals)delete updated[field.id];onChange(updated);};return <fieldset><legend>{question.text}</legend>{question.fields?.map(field=>{const active=!field.condition||objectValue[field.condition.field]===field.condition.equals;if(!active)return null;const label=fieldLabels[field.id]??field.id;return <div key={field.id}><span>{label}</span>{field.type==='single'?<>{field.options?.map(option=><label key={option.id}><input type="radio" name={`${question.id}-${field.id}`} checked={objectValue[field.id]===option.id} onChange={()=>setField(field.id,option.id)}/>{option.label}</label>)}</>:field.type==='multiple'?<>{field.options?.map(option=>{const selected=Array.isArray(objectValue[field.id])?objectValue[field.id] as string[]:[];return <label key={option.id}><input type="checkbox" checked={selected.includes(option.id)} disabled={!selected.includes(option.id)&&selected.length>=(field.maxSelections??field.options?.length??0)} onChange={()=>setField(field.id,selected.includes(option.id)?selected.filter(x=>x!==option.id):[...selected,option.id])}/>{option.label}</label>;})}</>:field.type==='integer'?<input aria-label={label} type="number" min={field.min} max={field.max} value={(objectValue[field.id] as number|undefined)??''} onChange={e=>{if(e.target.value===''){const updated={...objectValue};delete updated[field.id];onChange(updated);}else setField(field.id,Number(e.target.value));}}/>:field.type==='audio'?<p>{label}（语音输入待实现）</p>:<textarea aria-label={label} maxLength={field.maxLength} value={(objectValue[field.id] as string|undefined)??''} onChange={e=>setField(field.id,e.target.value)}/>}</div>;})}</fieldset>; }
  if(question.type==='scale') return <input aria-label={question.text} type="range" min={question.min} max={question.max} value={(value as number|undefined)??question.min} onChange={e=>onChange(Number(e.target.value))}/>;
  if(question.type==='experience') return <textarea aria-label={question.text} maxLength={question.maxLength} value={(value as string)??''} onChange={e=>onChange(e.target.value)}/>;
  const selected=Array.isArray(value)?value:[],maximum=question.fields?.[0]?.maxSelections??question.maxSelections??question.options?.length??0;
  return <>{question.options?.map(option=><label key={option.id}><input type={question.type==='single'?'radio':'checkbox'} name={question.id} checked={question.type==='single'?value===option.id:selected.includes(option.id)} disabled={question.type==='multiple'&&!selected.includes(option.id)&&selected.length>=maximum} onChange={()=>question.type==='single'?onChange(option.id):onChange(selected.includes(option.id)?selected.filter(x=>x!==option.id):[...selected,option.id])}/>{option.label}</label>)}</>;
}
export const SubmittedNotice=({jobId}:{jobId:string})=><section><h2>已进入生成队列</h2><p>任务编号：{jobId}</p></section>;
const emit=(sessionId:string,eventType:string,metadata:Record<string,string>={})=>{void sendEvent(sessionId,eventType,metadata).catch(()=>undefined);};
const readDraft=(raw:string|null,fallback:DraftState):DraftState=>{if(!raw)return fallback;try{const value=JSON.parse(raw) as DraftState;return value&&typeof value.revision==='number'&&value.answers&&value.dirty?value:fallback;}catch{return fallback;}};
const equalAnswer=(left:AnswerValue|undefined,right:AnswerValue|undefined)=>JSON.stringify(left)===JSON.stringify(right);

export function AssessmentFlow(){
  const [session,setSession]=useState<Session|null>(null),[owner,setOwner]=useState(''),[draft,setDraft]=useState<DraftState>({revision:0,answers:{},dirty:{}}),[index,setIndex]=useState(0),[job,setJob]=useState<string|null>(null),[error,setError]=useState('');
  const current=useRef(draft), chain=useRef(Promise.resolve()), submitKey=useRef(sessionStorage.getItem('assessment:submit-key')||crypto.randomUUID());
  sessionStorage.setItem('assessment:submit-key',submitKey.current);
  const persist=(next:DraftState,id?:string)=>{current.current=next;setDraft(next);if(id&&owner)localStorage.setItem(cacheKey(owner,id),JSON.stringify(next));};
  useEffect(()=>{ensureIdentity().then(identity=>{setOwner(identity.ownerId);return getCurrent().then(x=>x.session??createSession()).then(s=>({identity,s}));}).then(({identity,s})=>{setSession(s);setJob(s.jobId??null);const cached=readDraft(localStorage.getItem(cacheKey(identity.ownerId,s.id)),{revision:s.revision,answers:{},dirty:{}});const merged=mergeServerDraft(cached,s);current.current=merged;setDraft(merged);emit(s.id,'assessment_start',{status:s.status});}).catch(()=>setError('暂时无法载入，答案缓存仍会保留。'));},[]);
  useEffect(()=>{if(!session||!session.questions.length)return;emit(session.id,'question_view',{questionId:session.questions[0].id});return()=>emit(session.id,'assessment_exit',{status:session.status});},[session]);
  if(job)return <SubmittedNotice jobId={job}/>; if(!session)return <main><p>{error||'正在载入测评…'}</p></main>;
  if(!session.questions.length)return <main><p>{error||'正在载入测评…'}</p></main>;
  const question=session.questions[index];
  const save=(qid:string)=>{chain.current=chain.current.then(async()=>{const before=current.current;if(!before.dirty[qid]||Object.prototype.hasOwnProperty.call(before.conflicts??{},qid))return;try{let sentValue=before.answers[qid],result;try{result=await saveAnswer(session.id,qid,sentValue,before.revision);}catch(error){if(!(error instanceof ApiError)||error.status!==409)throw error;const server=await getSession(session.id),latest=current.current,merged=mergeServerDraft(latest,server);if(equalAnswer(server.answers.find(answer=>answer.questionId===qid)?.value,latest.answers[qid])){persist({...merged,dirty:{...merged.dirty,[qid]:false}},session.id);setError('');return;}persist(merged,session.id);if(Object.prototype.hasOwnProperty.call(merged.conflicts??{},qid)){setError('另一处已修改此答案，请选择保留版本。');return;}sentValue=merged.answers[qid];result=await saveAnswer(session.id,qid,sentValue,server.revision);}const latest=current.current;persist({...latest,revision:result.revision,dirty:{...latest.dirty,[qid]:!equalAnswer(latest.answers[qid],sentValue)},baseAnswers:{...latest.baseAnswers,[qid]:sentValue}},session.id);emit(session.id,'assessment_save',{questionId:qid,status:'saved'});setError('');}catch{setError('保存失败，可重试；本机答案未清空。');}});};
  const change=(value:AnswerValue)=>{persist(updateAnswer(current.current,question.id,value),session.id);emit(session.id,'question_answer',{questionId:question.id});save(question.id);};
  const retry=()=>{for(const qid of Object.keys(current.current.dirty))if(current.current.dirty[qid])save(qid);};
  const conflictEntry=Object.entries(draft.conflicts??{})[0];
  const keepLocal=()=>{if(!conflictEntry)return;const [qid]=conflictEntry,next={...current.current,conflicts:{...current.current.conflicts}};delete next.conflicts![qid];persist(next,session.id);setError('');save(qid);};
  const useServer=()=>{if(!conflictEntry)return;const [qid,serverValue]=conflictEntry,next={...current.current,answers:{...current.current.answers},dirty:{...current.current.dirty,[qid]:false},conflicts:{...current.current.conflicts}};delete next.conflicts![qid];if(serverValue===undefined)delete next.answers[qid];else next.answers[qid]=serverValue;persist(next,session.id);setError('');};
  const complete=session.questions.every(q=>questionComplete(q,draft.answers[q.id]));
  const move=(to:number)=>{emit(session.id,to<index?'question_back':'question_view',{questionId:session.questions[to].id});setIndex(to);};
  const submit=()=>{chain.current.then(()=>{if(Object.values(current.current.dirty).some(Boolean)||Object.keys(current.current.conflicts??{}).length)throw new Error('unsaved');return submitSession(session.id,submitKey.current);}).then(x=>{emit(session.id,'assessment_submit',{status:'queued'});setJob(x.jobId);}).catch(()=>setError(Object.keys(current.current.conflicts??{}).length?'请先处理答案冲突。':Object.values(current.current.dirty).some(Boolean)?'仍有答案未保存，请先重试保存。':'提交失败，请重试；答案不会清空。'));};
  const hasUnsaved=Object.values(draft.dirty).some(Boolean);
  return <main>{session.demo&&<aside>演示数据：内容未经专家确认，仅用于流程展示。</aside>}<p>进度 {Object.keys(draft.answers).length}/40</p><h2>{index+1}. {question.text}</h2><QuestionInput question={question} value={draft.answers[question.id]} onChange={change}/>{error&&<p role="alert">{error}</p>}{conflictEntry?<div><button onClick={keepLocal}>保留本机答案</button><button onClick={useServer}>使用另一处答案</button></div>:hasUnsaved&&<button onClick={retry}>重试保存</button>}<nav><button disabled={index===0} onClick={()=>move(index-1)}>上一题</button><button disabled={index===39} onClick={()=>move(index+1)}>下一题</button></nav><button disabled={!complete} onClick={submit}>提交并进入生成队列</button></main>;
}
