// Generated by scripts/generate_contracts.py from Pydantic JSON Schema.
// Do not edit by hand.

export type Action = { readonly id: string; readonly title: string; readonly reason: Claim; readonly firstStep: string; readonly methodReferences: readonly (Reference)[]; readonly status: "pending" | "completed"; };

export type ActionPlanItem = { readonly day: 30 | 60 | 90; readonly actionIds: readonly (string)[]; readonly deliverable: string; };

export type ChatReply = { readonly messageId: string; readonly conclusion: Claim; readonly facts: readonly (Claim)[]; readonly inferences: readonly (Claim)[]; readonly recommendations: readonly (Claim)[]; readonly toValidate: readonly (Claim)[]; readonly factCandidates: readonly (Fact)[]; readonly createdAt: string; };

export type Claim = { readonly id: string; readonly text: string; readonly claimType: "fact" | "inference" | "recommendation" | "to_validate"; readonly references: readonly (Reference)[]; };

export type Core = { readonly type: TypeSummary | null; readonly keySummaries: KeySummaries; readonly radar: Radar | null; readonly evidence: readonly (Evidence)[]; readonly strengths: readonly (Strength)[]; readonly weaknesses: readonly (Claim)[]; readonly risk: Claim | null; readonly judgments: readonly (Claim)[]; };

export type Decisions = { readonly jobMatches: (JobMatch)[]; readonly explicitTargets: (JobMatch)[]; readonly preferredDirection: Claim | null; readonly alternativeDirection: Claim | null; readonly actions: (Action)[]; readonly actionPlan: readonly (ActionPlanItem)[]; readonly preparationSuggestions: readonly (Claim)[]; readonly counterEvidenceConditions: readonly (Claim)[]; };

export type Dimension = { readonly id: string; readonly name: string; readonly score: number | null; readonly description: string; readonly evidenceIds: readonly (string)[]; };

export type ErrorBody = { readonly code: string; readonly message: string; readonly requestId: string; readonly details?: {  }; };

export type ErrorEnvelope = { readonly error: ErrorBody; };

export type Evidence = { readonly id: string; readonly questionId: string | null; readonly answerId: string | null; readonly quote: string; readonly taskIds: readonly (string)[]; readonly sourceStatus: "verified_result" | "confirmed_self_report" | "behavior" | "preference" | "missing" | "conflict"; readonly verificationSource: string | null; readonly gaps: readonly (string)[]; readonly conflictGroupId: string | null; };

export type Fact = { readonly factId: string; readonly content: string; readonly sourceMessageId: string; readonly status: "candidate" | "confirmed" | "rejected" | "retracted"; readonly createdAt: string; readonly targetProfileField: "goal" | "preference" | "experience" | "feedback"; };

export type HardGate = { readonly requirementId: string; readonly status: "met" | "missing" | "unknown" | "conflict"; readonly evidenceIds: readonly (string)[]; readonly source: Reference; };

export type IndustryContext = { readonly point: Claim; readonly line: Claim; readonly plane: Claim; readonly system: Claim; readonly asOf: string | null; readonly references: readonly (Reference)[]; };

export type Interpretation = { readonly sections: readonly (InterpretationSection)[]; readonly aiUsageNotice: string; readonly reviewItems: readonly (string)[]; };

export type InterpretationSection = { readonly key: "core_judgment" | "job_impact" | "uncertainty" | "validation"; readonly claims: readonly (Claim)[]; };

export type Job = { readonly id: string; readonly status: "queued" | "running" | "ready" | "failed"; readonly stage: "validate" | "score" | "retrieve" | "generate" | "complete"; readonly reportId: string | null; readonly completedParts: readonly ("core" | "decisions" | "interpretation")[]; readonly failedParts: readonly (string)[]; readonly retryable: boolean; readonly attemptCount: number; readonly errorCode: string | null; };

export type JobMatch = { readonly id: string; readonly name: string; readonly jobSourceId: string | null; readonly jobVersion: string | null; readonly sourceStatus: "verified" | "template_provisional" | "unknown"; readonly tasks: readonly (JobTask)[]; readonly eligibility: "current" | "explore" | "clarify" | "exclude"; readonly strategyLabel: "steady" | "stretch" | "safe" | null; readonly strategyStatus: "ready" | "pending_method"; readonly taskCoverage: {  }; readonly evidenceStatus: "supported" | "self_report_pending" | "transfer_pending" | "gap" | "unknown" | "conflict"; readonly requirementComparisons: readonly (RequirementComparison)[]; readonly hardGates: readonly (HardGate)[]; readonly transfer: Transfer; readonly reason: Claim; readonly evidenceIds: readonly (string)[]; readonly gaps: readonly (string)[]; readonly risks: readonly (Claim)[]; readonly validationTask: Action; readonly industryContext: IndustryContext; };

export type JobTask = { readonly id: string; readonly name: string; };

export type KeySummaries = { readonly state: Claim; readonly advantage: Claim; readonly risk: Claim; };

export type Part_Core_ = { readonly status: "pending" | "running" | "ready" | "failed"; readonly data: Core | null; readonly errorCode: string | null; };

export type Part_Decisions_ = { readonly status: "pending" | "running" | "ready" | "failed"; readonly data: Decisions | null; readonly errorCode: string | null; };

export type Part_Interpretation_ = { readonly status: "pending" | "running" | "ready" | "failed"; readonly data: Interpretation | null; readonly errorCode: string | null; };

export type Radar = { readonly dimensions: (Dimension)[]; readonly scale: readonly [0, 100]; };

export type Reference = { readonly source: "answer" | "knowledge" | "report" | "profile" | "job_source" | "method"; readonly id: string; readonly version: string; readonly location?: string | null; };

export type Report = { readonly id: string; readonly assessmentId: string; readonly version: number; readonly demo: boolean; readonly status: "generating" | "partial" | "ready" | "failed"; readonly reviewStatus: "pending" | "confirmed" | "disputed"; readonly sourceVersions: SourceVersions; readonly inputHash: string; readonly createdAt: string; readonly core: Part_Core_; readonly decisions: Part_Decisions_; readonly interpretation: Part_Interpretation_; readonly tracking: Tracking; };

export type RequirementComparison = { readonly requirementId: string; readonly taskId: string; readonly capabilityId: string; readonly requirementType: "hard_gate" | "core" | "bonus"; readonly requiredLevel: "L0" | "L1" | "L2" | "L3" | "unknown"; readonly observedLevel: "L0" | "L1" | "L2" | "L3" | "unknown"; readonly judgmentStatus: "supported" | "self_report_pending" | "transfer_pending" | "gap" | "unknown" | "conflict"; readonly evidenceIds: readonly (string)[]; readonly requirementSource: Reference; };

export type Snapshot = { readonly id: string; readonly previousId: string | null; readonly createdAt: string; readonly reportIds: readonly (string)[]; readonly confirmedFacts: readonly (Fact)[]; readonly changeReason: string; };

export type SourceVersions = { readonly questionVersion: string; readonly ruleVersion: string; readonly jobTemplateVersion: string; readonly knowledgeIndexVersion: string; readonly promptVersion: string; readonly modelName: string; readonly embeddingModelVersion: string; readonly profileSnapshotId: string | null; };

export type Strength = { readonly dimensionId: string; readonly score: number | null; readonly evidenceIds: readonly (string)[]; readonly application: string; };

export type Tracking = { readonly status: "preview"; readonly nodes: readonly (TrackingNode)[]; };

export type TrackingNode = { readonly day: 7 | 30 | 90; readonly label: string; };

export type Transfer = { readonly level: "low" | "medium" | "high" | "unknown"; readonly provisional: boolean; readonly dimensions: readonly (TransferDimension)[]; readonly reason: Claim; };

export type TransferDimension = { readonly key: "core_task" | "industry_qualification" | "hard_skill" | "service_chain" | "responsibility_environment"; readonly status: "reusable" | "validate_in_context" | "training_needed" | "unknown" | "conflict"; readonly evidenceIds: readonly (string)[]; readonly requirementIds: readonly (string)[]; readonly references: readonly (Reference)[]; };

export type TypeSummary = { readonly id: string; readonly name: string; readonly summary: Claim; };
