"""initial versioned data model

Revision ID: 9d92db037fab
Revises:
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d92db037fab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('revision', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('question','rule','prompt','job_template','knowledge_index')", name='ck_content_kind'),
    sa.CheckConstraint("status IN ('draft','published','retired')", name='ck_content_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'revision', name='uq_content_kind_revision')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_date', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('version_pointers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['content_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', name='uq_current_pointer_kind')
    )
    op.create_table('assessment_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('question_version_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','submitted','generating','completed')", name='ck_session_status'),
    sa.CheckConstraint('revision >= 0', name='ck_session_revision'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'owner_id', name='uq_session_id_owner')
    )
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_sessions_owner_id'), ['owner_id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('index_version_id', sa.String(), nullable=False),
    sa.Column('chunk_key', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_version_id', 'chunk_key', name='uq_index_chunk')
    )
    op.create_table('profile_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('previous_id', sa.String(), nullable=True),
    sa.Column('report_ids', sa.JSON(), nullable=False),
    sa.Column('confirmed_facts', sa.JSON(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_id'], ['profile_snapshots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_snapshots_owner_id'), ['owner_id'], unique=False)

    op.create_table('assessment_answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_answer_session_question')
    )
    op.create_table('report_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('question_version_id', sa.String(), nullable=False),
    sa.Column('rule_version_id', sa.String(), nullable=False),
    sa.Column('job_template_version_id', sa.String(), nullable=False),
    sa.Column('knowledge_index_version_id', sa.String(), nullable=False),
    sa.Column('prompt_version_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('embedding_model_version', sa.String(), nullable=False),
    sa.Column('profile_snapshot_id', sa.String(), nullable=True),
    sa.Column('core', sa.JSON(), nullable=True),
    sa.Column('decisions', sa.JSON(), nullable=True),
    sa.Column('interpretation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("NOT (review_status = 'confirmed' AND status != 'ready')", name='ck_confirm_only_ready_report'),
    sa.CheckConstraint("review_status IN ('pending','confirmed','disputed')", name='ck_report_review_status'),
    sa.CheckConstraint("status IN ('generating','partial','ready','failed')", name='ck_report_status'),
    sa.CheckConstraint('version >= 1', name='ck_report_version'),
    sa.ForeignKeyConstraint(['assessment_id', 'owner_id'], ['assessment_sessions.id', 'assessment_sessions.owner_id'], name='fk_report_assessment_owner', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'version', name='uq_report_assessment_version')
    )
    with op.batch_alter_table('report_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_versions_owner_id'), ['owner_id'], unique=False)

    op.create_table('action_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('client_event_id', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'client_event_id', name='uq_feedback_idempotency')
    )
    op.create_table('job_matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('job_template_version_id', sa.String(), nullable=False),
    sa.Column('match_status', sa.String(), nullable=False),
    sa.Column('evidence_sufficiency', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('current_fit', sa.Float(), nullable=True),
    sa.Column('potential_fit', sa.Float(), nullable=True),
    sa.Column('current_basis', sa.Text(), nullable=False),
    sa.Column('potential_basis', sa.Text(), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('validation_task', sa.JSON(), nullable=False),
    sa.Column('industry_context', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'owner_id', name='uq_report_profile_review')
    )
    op.create_table('report_chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'report_id', name='uq_owner_report_chat')
    )
    op.create_table('report_generation_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('source_versions', sa.JSON(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('profile_snapshot_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(), nullable=True),
    sa.Column('lease_token', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('report_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','ready','failed')", name='ck_generation_job_status'),
    sa.CheckConstraint('attempt_count >= 0 AND attempt_count <= 3', name='ck_generation_attempt_count'),
    sa.CheckConstraint('lease_token >= 0', name='ck_generation_lease_token'),
    sa.ForeignKeyConstraint(['assessment_id', 'owner_id'], ['assessment_sessions.id', 'assessment_sessions.owner_id'], name='fk_generation_job_assessment_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', name='uq_generation_job_report')
    )
    with op.batch_alter_table('report_generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_generation_jobs_owner_id'), ['owner_id'], unique=False)

    op.create_table('action_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['report_generation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'attempt_number', name='uq_job_attempt')
    )
    op.create_table('report_chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('client_message_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['report_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'client_message_id', name='uq_chat_message_idempotency')
    )
    op.create_table('conversation_facts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('source_message_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('target_profile_field', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['report_chat_messages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_decision_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('fact_id', sa.String(), nullable=False),
    sa.Column('client_decision_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resulting_snapshot_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fact_id'], ['conversation_facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resulting_snapshot_id'], ['profile_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'client_decision_id', name='uq_fact_decision_idempotency')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_decision_events')
    op.drop_table('conversation_facts')
    op.drop_table('report_chat_messages')
    op.drop_table('generation_attempts')
    op.drop_table('action_events')
    with op.batch_alter_table('report_generation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_generation_jobs_owner_id'))

    op.drop_table('report_generation_jobs')
    op.drop_table('report_chat_sessions')
    op.drop_table('profile_reviews')
    op.drop_table('job_matches')
    op.drop_table('feedback_events')
    op.drop_table('evidence_items')
    op.drop_table('action_items')
    with op.batch_alter_table('report_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_versions_owner_id'))

    op.drop_table('report_versions')
    op.drop_table('assessment_answers')
    with op.batch_alter_table('profile_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_snapshots_owner_id'))

    op.drop_table('profile_snapshots')
    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_sessions_owner_id'))

    op.drop_table('assessment_sessions')
    op.drop_table('version_pointers')
    op.drop_table('users')
    op.drop_table('knowledge_documents')
    op.drop_table('content_versions')
    op.drop_table('audit_logs')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
