#!/usr/bin/env python3
"""Export Pydantic JSON Schema and deterministically render its TypeScript types."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.contracts.errors import ErrorEnvelope  # noqa: E402
from app.contracts.report import ChatReply, Fact, Job, Report, Snapshot  # noqa: E402


SCHEMA_PATH = ROOT / "frontend" / "src" / "api" / "schema.json"
TYPES_PATH = ROOT / "frontend" / "src" / "api" / "schema.ts"


def schemas() -> dict[str, Any]:
    models = [Report, Job, Fact, ChatReply, Snapshot, ErrorEnvelope]
    definitions: dict[str, Any] = {}
    roots: dict[str, Any] = {}
    for model in models:
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        definitions.update(schema.pop("$defs", {}))
        roots[model.__name__] = schema
    definitions.update(roots)
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "CareerAssessmentContracts",
        "$defs": definitions,
    }


def ts_type(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "const" in node:
        return json.dumps(node["const"], ensure_ascii=False)
    if "enum" in node:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in node["enum"])
    if "anyOf" in node:
        return " | ".join(ts_type(choice) for choice in node["anyOf"])
    if "prefixItems" in node:
        return "readonly [" + ", ".join(ts_type(item) for item in node["prefixItems"]) + "]"
    if node.get("type") == "array":
        prefix = "readonly " if node.get("maxItems") == node.get("minItems") else ""
        return f"{prefix}({ts_type(node.get('items', {}))})[]"
    if node.get("type") == "object":
        properties = node.get("properties", {})
        required = set(node.get("required", []))
        fields = [f"readonly {name}{'' if name in required else '?'}: {ts_type(value)};" for name, value in properties.items()]
        return "{ " + " ".join(fields) + " }"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(node.get("type"), "unknown")


def collect_definitions(root: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return root["$defs"]


def typescript(root: dict[str, Any]) -> str:
    lines = ["// Generated by scripts/generate_contracts.py from Pydantic JSON Schema.", "// Do not edit by hand.", ""]
    for name, definition in sorted(collect_definitions(root).items()):
        lines.append(f"export type {name} = {ts_type(definition)};")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = schemas()
    outputs = {
        SCHEMA_PATH: json.dumps(root, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        TYPES_PATH: typescript(root),
    }
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, content in outputs.items() if not path.exists() or path.read_text() != content]
        if stale:
            print("Generated contracts are stale: " + ", ".join(stale))
            return 1
        return 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
